
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H723ZG"

[build]
target = "thumbv7em-none-eabihf"

rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[unstable]
build-std = ["alloc", "core"]

[env]
DEFMT_LOG = "info"
